version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: icn
      POSTGRES_PASSWORD: icn_dev
      POSTGRES_DB: icn_node
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U icn -d icn_node"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  postgres_data:
