"""Initial schema with orgs, invoices, audit log

Revision ID: 411f4d556606
Revises: 
Create Date: 2025-09-10 18:20:23.099579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411f4d556606'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prev_hash', sa.String(length=128), nullable=True),
    sa.Column('row_hash', sa.String(length=128), nullable=False),
    sa.Column('op_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('payload_hash', sa.String(length=128), nullable=False),
    sa.Column('signature', sa.String(length=1024), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_row_hash'), 'audit_log', ['row_hash'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('operations_count', sa.Integer(), nullable=False),
    sa.Column('merkle_root', sa.String(length=128), nullable=False),
    sa.Column('prev_checkpoint_hash', sa.String(length=128), nullable=True),
    sa.Column('signature', sa.String(length=1024), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkpoints_date'), 'checkpoints', ['date'], unique=False)
    op.create_table('orgs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('urn', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.String(length=512), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orgs_urn'), 'orgs', ['urn'], unique=True)
    op.create_table('attestations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('attestor_org_id', sa.Integer(), nullable=False),
    sa.Column('claims', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('signature', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attestor_org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attestations_attestor_org_id'), 'attestations', ['attestor_org_id'], unique=False)
    op.create_index('ix_attestations_subject', 'attestations', ['subject_type', 'subject_id'], unique=False)
    op.create_index(op.f('ix_attestations_subject_id'), 'attestations', ['subject_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('from_org_id', sa.Integer(), nullable=False),
    sa.Column('to_org_id', sa.Integer(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('terms', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_history', sa.JSON(), nullable=False),
    sa.Column('signatures', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=128), nullable=True),
    sa.Column('row_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_invoices_from_org_id'), 'invoices', ['from_org_id'], unique=False)
    op.create_index('ix_invoices_from_to', 'invoices', ['from_org_id', 'to_org_id'], unique=False)
    op.create_index(op.f('ix_invoices_row_hash'), 'invoices', ['row_hash'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_to_org_id'), 'invoices', ['to_org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_to_org_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_row_hash'), table_name='invoices')
    op.drop_index('ix_invoices_from_to', table_name='invoices')
    op.drop_index(op.f('ix_invoices_from_org_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_attestations_subject_id'), table_name='attestations')
    op.drop_index('ix_attestations_subject', table_name='attestations')
    op.drop_index(op.f('ix_attestations_attestor_org_id'), table_name='attestations')
    op.drop_table('attestations')
    op.drop_index(op.f('ix_orgs_urn'), table_name='orgs')
    op.drop_table('orgs')
    op.drop_index(op.f('ix_checkpoints_date'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_audit_log_row_hash'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
